vich_uploader:
    db_driver: orm

    mappings:
        books:
            uri_prefix: /upload/images
            upload_destination: '%kernel.project_dir%/public/upload/images'
            delete_on_update: true
            delete_on_remove: true
